#!/usr/bin/env bash
#installs ngnix webserver 

# Update package list and install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Configure Nginx to listen on port 80
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx restart

# Create a default HTML page
echo "Hello World!" | sudo tee /var/www/html/index.html
