#!/usr/bin/env bash
#installs ngnix webserver 

apt-get update

# Install nginx
apt-get install nginx -y

# Create the "Hello World!" HTML file
echo "Hello World!" /var/www/html/index.html

# Create a custom nginx configuration
printf %s 'server {
    listen 80;
        listen [::]:80;
	    root   /var/www/html;
	        index  index.html;
	}' > /etc/nginx/sites-available/default

# Restart nginx service
sudo service nginx restart
~                           
