#!/usr/bin/env bash
# A Script that configures a new Ubuntu machine to Perform a 301-redirection

# Updating Packages before Installations
sudo apt-get update
sudo apt-get install -y nginx

# Creating an index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Performing a 301 Redirection
redirection_url="https:\/\/github.com\/emmanueladdo"
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me $redirection_url permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-available/default

# Restarting Nginx service
sudo service nginx restart
