#!/usr/bin/env bash
# A Script that configures a new Ubuntu machine and headerfile 

sudo apt-get update
sudo apt-get install -y nginx

# Creating an index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Performing a 301 Redirection
redirection_url="https:\/\/github.com\/emmanueladdo"
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me $redirection_url permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-available/default

# Creates a custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
replacement_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html; \n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$replacement_string/" /etc/nginx/sites-available/default

# Creates an HTTP response header
sudo sed -i "/server_name _/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default

#test for syntax errors
sudo nginx -t 

# Restarting Nginx service
sudo service nginx restart

