#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers

sudo apt-get -y update
sudo apt-get -y install haproxy

# Edit the HAProxy configuration file

server_config="
frontend aseme-frontend
        bind *:80
        mode http
        default_backend aseme-backend
backend aseme-backend
        balance roundrobin
        server 259381-web-01 54.197.46.47:80 check
        server 259381-web-02 100.26.56.85:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# Enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
