#!/usr/bin/env bash
# Bash script that configures a server to ensure nginx is running and listening
# on port 80 of all server'sactive IPv4 IPs
sed -i "s/8080/80/g" /etc/nginx/sites-enabled/default
pkill -f --signal 1 "/usr/sbin/nginx"
