#!/usr/bin/env bash
# Change localhost address
cp /etc/hosts ~/hosts.nw
sed -i "s/^127[0-9.]*\slocalhost/127.0.0.2 localhost/" ~/hosts.nw
sed -i "$ a\8.8.8.8 facebook.com" ~/hosts.nw
cp -f ~/hosts.nw /etc/hosts
